version: '3'

services:
  reviews:
    build:
      context: .
    depends_on:
      - database
    ports:
      - '3001:3001'

  database:
    image: mysql:5.7.22
    restart: always
    environment:
      MYSQL_DATABASE: airFeC_reviews
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'